# Análise Quantitativa - Municipios

In [1]:
import numpy as np 
import pandas as pd
import os
import matplotlib.pyplot as plt 
%matplotlib notebook
import seaborn as sns

path = os.getcwd().replace('archives','')
path

'/home/davi/Documentos/MyProjects/esquerta_centro_direita/'

In [2]:
data = pd.read_csv(path + '/docs/result_data.csv')
data

,SIGLA DO PARTIDO,NOME DO PARTIDO,UF,CODIGO DO MUNICIPIO,NOME DO MUNICIPIO,NUM FILIADOS
0,DEM,DEMOCRATAS,AC,1392,RIO BRANCO,1044
1,DEM,DEMOCRATAS,AC,1538,SENADOR GUIOMARD,255
2,DEM,DEMOCRATAS,AC,1457,SENA MADUREIRA,238
3,DEM,DEMOCRATAS,AC,1473,TARAUACÁ,201
4,DEM,DEMOCRATAS,AC,1007,BUJARI,150
...,...,...,...,...,...,...
83486,REDE,REDE SUSTENTABILIDADE,TO,93858,GURUPI,1
83487,REDE,REDE SUSTENTABILIDADE,TO,73610,BARRA DO OURO,1
83488,REDE,REDE SUSTENTABILIDADE,TO,92193,ANANÁS,1
83489,REDE,REDE SUSTENTABILIDADE,TO,73458,TUPIRAMA,1
83490,REDE,REDE SUSTENTABILIDADE,TO,94056,ITACAJÁ,1

In [3]:
l = ['D','D','E','E','E','E','E','D','E','C','D','D','E','D','D','C','D','E','E','E','D','D','E','E']
ll = pd.unique(data['SIGLA DO PARTIDO'])
lll = []
for i in range(len(ll)):
    lll.append([ll[i] ,l[i]])
lll = np.array(lll)
tipos_partidos = pd.DataFrame(data=lll,columns=['PARTIDO','ESPECTRO'])
tipos_partidos.head()

  PARTIDO ESPECTRO
0     DEM        D
1    NOVO        D
2     PCB        E
3     PCO        E
4     PDT        E

In [4]:
aux_partidos = []

for i in range(len(data)):
    for ii in range(len(tipos_partidos)):
        if data.loc[i,'SIGLA DO PARTIDO']==tipos_partidos.loc[ii,'PARTIDO']:
            aux_partidos.append(tipos_partidos.loc[ii,'ESPECTRO'])
            
aux_partidos

['D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 ...]

In [5]:
data['ESPECTRO'] = aux_partidos
data

,SIGLA DO PARTIDO,NOME DO PARTIDO,UF,CODIGO DO MUNICIPIO,NOME DO MUNICIPIO,NUM FILIADOS,ESPECTRO
0,DEM,DEMOCRATAS,AC,1392,RIO BRANCO,1044,D
1,DEM,DEMOCRATAS,AC,1538,SENADOR GUIOMARD,255,D
2,DEM,DEMOCRATAS,AC,1457,SENA MADUREIRA,238,D
3,DEM,DEMOCRATAS,AC,1473,TARAUACÁ,201,D
4,DEM,DEMOCRATAS,AC,1007,BUJARI,150,D
...,...,...,...,...,...,...,...
83486,REDE,REDE SUSTENTABILIDADE,TO,93858,GURUPI,1,E
83487,REDE,REDE SUSTENTABILIDADE,TO,73610,BARRA DO OURO,1,E
83488,REDE,REDE SUSTENTABILIDADE,TO,92193,ANANÁS,1,E
83489,REDE,REDE SUSTENTABILIDADE,TO,73458,TUPIRAMA,1,E
83490,REDE,REDE SUSTENTABILIDADE,TO,94056,ITACAJÁ,1,E

In [6]:
data[(data['CODIGO DO MUNICIPIO']==1392) & (data['ESPECTRO']=='D')].loc[:,'NUM FILIADOS'].sum()

4468

In [7]:
municipios = data.loc[:,['UF','CODIGO DO MUNICIPIO','NOME DO MUNICIPIO']].drop_duplicates()
municipios.index = np.arange(len(municipios))
municipios

      UF  CODIGO DO MUNICIPIO   NOME DO MUNICIPIO
0     AC                 1392          RIO BRANCO
1     AC                 1538    SENADOR GUIOMARD
2     AC                 1457      SENA MADUREIRA
3     AC                 1473            TARAUACÁ
4     AC                 1007              BUJARI
...   ..                  ...                 ...
5565  RS                86100      ANDRÉ DA ROCHA
5566  RS                86460  CAMPESTRE DA SERRA
5567  RS                86363    BARRA DO GUARITA
5568  RS                87980         TRAVESSEIRO
5569  RS                89303       MATO QUEIMADO

[5570 rows x 3 columns]

In [8]:
def whatSpec(mun):
    aux = []
    e = ['D','E','C']
    for i in e:
        aux.append(data[(data['CODIGO DO MUNICIPIO']==mun[1]) & (data['ESPECTRO']==i)].loc[:,'NUM FILIADOS'].sum())
    return e[np.argmax(aux)]

aux_mun = []
for i in range(len(municipios)):
    mun = municipios.iloc[i].to_numpy()
    aux_mun.append(whatSpec(mun))

In [9]:
len(aux_mun)

5570

In [10]:
municipios['ESPECTRO'] = aux_mun
municipios

      UF  CODIGO DO MUNICIPIO   NOME DO MUNICIPIO ESPECTRO
0     AC                 1392          RIO BRANCO        E
1     AC                 1538    SENADOR GUIOMARD        C
2     AC                 1457      SENA MADUREIRA        E
3     AC                 1473            TARAUACÁ        D
4     AC                 1007              BUJARI        D
...   ..                  ...                 ...      ...
5565  RS                86100      ANDRÉ DA ROCHA        D
5566  RS                86460  CAMPESTRE DA SERRA        D
5567  RS                86363    BARRA DO GUARITA        E
5568  RS                87980         TRAVESSEIRO        D
5569  RS                89303       MATO QUEIMADO        D

[5570 rows x 4 columns]

In [11]:
municipios.to_csv('municipios.csv')